### ISSUE TITLE
WEVE GOT A ISHUE....

### ISSUE THREAD

**Issue by epicnesslol** [netguru/help#97]
help!!! Totoal bug stuck in tardis temporal engin gone crazy

https://www.mediafire.com/?2sllqcnjm5grv3a

**Comment by lubieniebieski** [comment]
I don't think minecraft movie is related in any way to the project:)

**Comment by epicnesslol** [comment]
if you wach it it is a photo video of the bug

**Comment by lubieniebieski** [comment]
what's the bug then?

**Comment by epicnesslol** [comment]
i was messing around with orespawn and a farm spawner landed on the counsole....the temporal engine want crazy...and i was stuch in the tardis forever
